/*
 * Project: Jacqueline Taylor & Friends
 *
 * Created on Sun Apr 24 2022
 *
 * Filename: Head.js
 *
 * Copyright (c) 2022 Bujisoft
 */

import Head from 'next/head';

const Mbhead = () => {
    return (
    <Head>
        <title>Jacqueline Taylor & Friends ❤️</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    )
}
export default Mbhead